-- ************************************** "public"."Character"

CREATE TABLE IF NOT EXISTS "public"."Character"
(
 "id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CONSTRAINT "PK_Character" PRIMARY KEY ( "id" )
)
WITH (
 USER_CATALOG_TABLE=TRUE
);

COMMENT ON TABLE "public"."Character" IS 'Basic information about Character';

COMMENT ON COLUMN "public"."Character"."id" IS 'Autogenerated ID of Character';

-- ************************************** "public"."Character_Attribute"

CREATE TABLE IF NOT EXISTS "public"."Character_Attribute"
(
 "character_id" bigint NOT NULL,
 "name"         character varying(50) NOT NULL,
 "value"        real NULL,
 "text"         text NULL,
 "id"           bigint NULL,
 "interval"     interval NULL,
 "timestamp"    timestamptz NULL,
 "bool"         boolean NULL,
 CONSTRAINT "PK_Character_Name" PRIMARY KEY ( "character_id", "name" ),
 CONSTRAINT "FK_Character_Attribute" FOREIGN KEY ( "character_id" ) REFERENCES "public"."Character" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "FK_Character_Attribute" ON "public"."Character_Attribute"
(
 "character_id"
);

COMMENT ON TABLE "public"."Character_Attribute" IS 'Attributes associated with Character';

COMMENT ON COLUMN "public"."Character_Attribute"."character_id" IS 'Character''s ID';
COMMENT ON COLUMN "public"."Character_Attribute"."name" IS 'Name of Character''s Attribute';
COMMENT ON COLUMN "public"."Character_Attribute"."value" IS 'Value of Character''s Attribute';
COMMENT ON COLUMN "public"."Character_Attribute"."text" IS 'Text of Attribute';
COMMENT ON COLUMN "public"."Character_Attribute"."id" IS 'External ID of Attribute';
COMMENT ON COLUMN "public"."Character_Attribute"."interval" IS 'Interval of Attribute';
COMMENT ON COLUMN "public"."Character_Attribute"."timestamp" IS 'Timestamp with Timezone of Attribute';
COMMENT ON COLUMN "public"."Character_Attribute"."bool" IS 'Boolean of Attribute';

-- ************************************** "public"."Owner"

CREATE TABLE IF NOT EXISTS "public"."Owner"
(
 "character_id" bigint NOT NULL,
 "server_id"    bigint NOT NULL,
 "user_id"      bigint NOT NULL,
 CONSTRAINT "PK_Character_Owner" PRIMARY KEY ( "character_id" ),
 CONSTRAINT "FK_Character_Owner" FOREIGN KEY ( "character_id" ) REFERENCES "public"."Character" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "FK_Character_Owner" ON "public"."Owner"
(
 "character_id"
);

COMMENT ON TABLE "public"."Owner" IS 'Owner association for Character';

COMMENT ON COLUMN "public"."Owner"."character_id" IS 'ID of Owned Character';
COMMENT ON COLUMN "public"."Owner"."server_id" IS 'ID of Associated Server';
COMMENT ON COLUMN "public"."Owner"."user_id" IS 'ID of Owning User';

-- ************************************** "public"."Item"

CREATE TABLE IF NOT EXISTS "public"."Item"
(
 "id" int NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 "name"     VARCHAR(50) NOT NULL,
 CONSTRAINT "PK_Item" PRIMARY KEY ( "id" )
);

COMMENT ON TABLE "public"."Item" IS 'Item metadata';
COMMENT ON COLUMN "public"."Item"."id" IS 'Autogenerated ID for this Item';
COMMENT ON COLUMN "public"."Item"."name" IS 'Base name for this Item';

-- ************************************** "public"."Item_Attribute"

CREATE TABLE IF NOT EXISTS "public"."Item_Attribute"
(
 "item_id"   int NOT NULL,
 "name"      character varying(50) NOT NULL,
 "value"     real NULL,
 "text"      text NULL,
 "id"        bigint NULL,
 "interval"  interval NULL,
 "timestamp" timestamptz NULL,
 "bool"      boolean NULL,
 CONSTRAINT "PK_ItemName" PRIMARY KEY ( "item_id", "name" ),
 CONSTRAINT "FK_Item_Attribute" FOREIGN KEY ( "item_id" ) REFERENCES "public"."Item" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "FK_Item_Attribute" ON "public"."Item_Attribute"
(
 "item_id"
);

COMMENT ON TABLE "public"."Item_Attribute" IS 'Attributes associated with Item';

COMMENT ON COLUMN "public"."Item_Attribute"."item_id" IS 'Item''s ID';
COMMENT ON COLUMN "public"."Item_Attribute"."name" IS 'Name of Item''s Attribute';
COMMENT ON COLUMN "public"."Item_Attribute"."value" IS 'Value of Item''s Attribute';
COMMENT ON COLUMN "public"."Item_Attribute"."text" IS 'Text of Attribute';
COMMENT ON COLUMN "public"."Item_Attribute"."id" IS 'External ID of Attribute';
COMMENT ON COLUMN "public"."Item_Attribute"."interval" IS 'Interval of Attribute';
COMMENT ON COLUMN "public"."Item_Attribute"."timestamp" IS 'Timestamp with Timezone of Attribute';
COMMENT ON COLUMN "public"."Item_Attribute"."bool" IS 'Boolean of Attribute';
-- ************************************** "public"."Location"

CREATE TABLE IF NOT EXISTS "public"."Location"
(
 "id"          int NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 "name"        text NOT NULL,
 "description" text NOT NULL,
 CONSTRAINT "PK_Location" PRIMARY KEY ( "id" )
);

COMMENT ON TABLE "public"."Location" IS 'Location metadata';
COMMENT ON COLUMN "public"."Location"."id" IS 'Autogenerated ID of this Location';
COMMENT ON COLUMN "public"."Location"."name" IS 'Name of this Location';
COMMENT ON COLUMN "public"."Location"."description" IS 'Description of this Location';

-- ************************************** "public"."Location_Attribute"

CREATE TABLE IF NOT EXISTS "public"."Location_Attribute"
(
 "location_id" int NOT NULL,
 "name"        character varying(50) NOT NULL,
 "value"       real NULL,
 "text"        text NULL,
 "id"          bigint NULL,
 "interval"    interval NULL,
 "timestamp"   timestamptz NULL,
 "bool"        boolean NULL,
 CONSTRAINT "PK_Location_Name" PRIMARY KEY ( "location_id", "name" ),
 CONSTRAINT "FK_Location_Attribute" FOREIGN KEY ( "location_id" ) REFERENCES "public"."Location" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "FK_Location_Attribute" ON "public"."Location_Attribute"
(
 "location_id"
);

COMMENT ON TABLE "public"."Location_Attribute" IS 'Attributes associated with Location';

COMMENT ON COLUMN "public"."Location_Attribute"."location_id" IS 'Location''s ID';
COMMENT ON COLUMN "public"."Location_Attribute"."name" IS 'Name of Location''s Attribute';
COMMENT ON COLUMN "public"."Location_Attribute"."value" IS 'Value of Location''s Attribute';
COMMENT ON COLUMN "public"."Location_Attribute"."text" IS 'Text of Attribute';
COMMENT ON COLUMN "public"."Location_Attribute"."id" IS 'External ID of Attribute';
COMMENT ON COLUMN "public"."Location_Attribute"."interval" IS 'Interval of Attribute';
COMMENT ON COLUMN "public"."Location_Attribute"."timestamp" IS 'Timestamp with Timezone of Attribute';
COMMENT ON COLUMN "public"."Location_Attribute"."bool" IS 'Boolean of Attribute';
-- ************************************** "public"."Event"

CREATE TABLE IF NOT EXISTS "public"."Event"
(
 "id"          int NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 "name"        text NOT NULL,
 "description" text NOT NULL,
 "start_date"  timestamptz NOT NULL,
 "end_date"    timestamptz NOT NULL,
 CONSTRAINT "PK_Event" PRIMARY KEY ( "id" )
);

COMMENT ON TABLE "public"."Event" IS 'Event metadata';
COMMENT ON COLUMN "public"."Event"."id" IS 'Autogenerated ID of this Event';
COMMENT ON COLUMN "public"."Event"."name" IS 'Name of this Event';
COMMENT ON COLUMN "public"."Event"."description" IS 'Description of this Event';
COMMENT ON COLUMN "public"."Event"."start_date" IS 'Timestamp of start of this Event';
COMMENT ON COLUMN "public"."Event"."end_date" IS 'Timestamp of end of this Event';

-- ************************************** "public"."Event_Attribute"

CREATE TABLE IF NOT EXISTS "public"."Event_Attribute"
(
 "event_id"  int NOT NULL,
 "name"      character varying(50) NOT NULL,
 "value"     real NULL,
 "text"      text NULL,
 "id"        bigint NULL,
 "interval"  interval NULL,
 "timestamp" timestamptz NULL,
 "bool"      boolean NULL,
 CONSTRAINT "PK_Event_Name" PRIMARY KEY ( "event_id", "name" ),
 CONSTRAINT "FK_Event_Attribute" FOREIGN KEY ( "event_id" ) REFERENCES "public"."Event" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "FK_Event_Attribute" ON "public"."Event_Attribute"
(
 "event_id"
);

COMMENT ON TABLE "public"."Event_Attribute" IS 'Attributes associated with Event';

COMMENT ON COLUMN "public"."Event_Attribute"."event_id" IS 'Event''s ID';
COMMENT ON COLUMN "public"."Event_Attribute"."name" IS 'Name of Event''s Attribute';
COMMENT ON COLUMN "public"."Event_Attribute"."value" IS 'Value of Event''s Attribute';
COMMENT ON COLUMN "public"."Event_Attribute"."text" IS 'Text of Attribute';
COMMENT ON COLUMN "public"."Event_Attribute"."id" IS 'External ID of Attribute';
COMMENT ON COLUMN "public"."Event_Attribute"."interval" IS 'Interval of Attribute';
COMMENT ON COLUMN "public"."Event_Attribute"."timestamp" IS 'Timestamp with Timezone of Attribute';
COMMENT ON COLUMN "public"."Event_Attribute"."bool" IS 'Boolean of Attribute';
-- ************************************** "public"."Instance"

CREATE TABLE IF NOT EXISTS "public"."Instance"
(
 "id"          bigint NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 "name"        VARCHAR(50) NOT NULL,
 "item_id"     int NOT NULL,
 "location_id" int NULL,
 "event_id"    int NULL,
 CONSTRAINT "PK_Instance" PRIMARY KEY ( "id" ),
 CONSTRAINT "FK_Event_Instance" FOREIGN KEY ( "event_id" ) REFERENCES "public"."Event" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT "FK_Item_Instance" FOREIGN KEY ( "item_id" ) REFERENCES "public"."Item" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT "FK_Location_Instance" FOREIGN KEY ( "location_id" ) REFERENCES "public"."Location" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "FK_Event_Instance" ON "public"."Instance"
(
 "event_id"
);

CREATE INDEX "FK_Item_Instance" ON "public"."Instance"
(
 "item_id"
);

CREATE INDEX "FK_Location_Instance" ON "public"."Instance"
(
 "location_id"
);

COMMENT ON TABLE "public"."Instance" IS 'Instance metadata';
COMMENT ON COLUMN "public"."Instance"."id" IS 'Autogenerated ID of this Instance';
COMMENT ON COLUMN "public"."Instance"."name" IS 'Name of Instantiated Item';
COMMENT ON COLUMN "public"."Instance"."item_id" IS 'ID of Item this Instance is based on';
COMMENT ON COLUMN "public"."Instance"."location_id" IS 'ID of Locatin this Instance is related to';
COMMENT ON COLUMN "public"."Instance"."event_id" IS 'ID of Event this Instance is related to';

-- ************************************** "public"."Instance_Attribute"

CREATE TABLE IF NOT EXISTS "public"."Instance_Attribute"
(
 "instance_id" bigint NOT NULL,
 "name"        character varying(50) NOT NULL,
 "value"       real NULL,
 "text"        text NULL,
 "id"          bigint NULL,
 "interval"    interval NULL,
 "timestamp"   timestamptz NULL,
 "bool"        boolean NULL,
 CONSTRAINT "PK_Instance_Name" PRIMARY KEY ( "name" ),
 CONSTRAINT "FK_Instance_Attribute" FOREIGN KEY ( "instance_id" ) REFERENCES "public"."Instance" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "FK_Instance_Attribute" ON "public"."Instance_Attribute"
(
 "instance_id"
);

COMMENT ON TABLE "public"."Instance_Attribute" IS 'Attributes associated with Instance';
COMMENT ON COLUMN "public"."Instance_Attribute"."instance_id" IS 'Instance''s ID';
COMMENT ON COLUMN "public"."Instance_Attribute"."name" IS 'Name of Instance''s Attribute';
COMMENT ON COLUMN "public"."Instance_Attribute"."value" IS 'Value of Instance''s Attribute';
COMMENT ON COLUMN "public"."Instance_Attribute"."text" IS 'Text of Attribute';
COMMENT ON COLUMN "public"."Instance_Attribute"."id" IS 'External ID of Attribute';
COMMENT ON COLUMN "public"."Instance_Attribute"."interval" IS 'Interval of Attribute';
COMMENT ON COLUMN "public"."Instance_Attribute"."timestamp" IS 'Timestamp with Timezone of Attribute';
COMMENT ON COLUMN "public"."Instance_Attribute"."bool" IS 'Boolean of Attribute';
-- ************************************** "public"."Character_Inventory"

CREATE TABLE IF NOT EXISTS "public"."Character_Inventory"
(
 "character_id" bigint NOT NULL,
 "instance_id"  bigint NOT NULL,
 "quantity"     real NOT NULL DEFAULT 1,
 CONSTRAINT "PK_Character_Instance" PRIMARY KEY ( "character_id", "instance_id" ),
 CONSTRAINT "FK_Instance_Inventory" FOREIGN KEY ( "instance_id" ) REFERENCES "public"."Instance" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT "FK_Character_Inventory" FOREIGN KEY ( "character_id" ) REFERENCES "public"."Character" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "FK_CharacterInstance" ON "public"."Character_Inventory"
(
 "instance_id"
);

CREATE INDEX "FK_CharacterInventory" ON "public"."Character_Inventory"
(
 "character_id"
);

COMMENT ON TABLE "public"."Character_Inventory" IS 'Character''s Inventory';

COMMENT ON COLUMN "public"."Character_Inventory"."quantity" IS 'Amount of instance in Character''s inventory';

COMMENT ON COLUMN "public"."Character_Inventory"."character_id" IS 'Character''s inventory';

COMMENT ON COLUMN "public"."Character_Inventory"."instance_id" IS 'Instance in this inventory';

-- ************************************** "public"."Transaction"

CREATE TABLE IF NOT EXISTS "public"."Transaction"
(
 "id"        bigint NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 "timestamp" timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT "PK_Transaction" PRIMARY KEY ( "id" )
);

COMMENT ON TABLE "public"."Transaction" IS 'Transaction metadata';

COMMENT ON COLUMN "public"."Transaction"."id" IS 'Autogenerated ID of this Transaction';
COMMENT ON COLUMN "public"."Transaction"."timestamp" IS 'When this transaction happened';

-- ************************************** "public"."Transaction_Instances"

CREATE TABLE IF NOT EXISTS "public"."Transaction_Instances"
(
 "transaction_id" bigint NOT NULL,
 "instance_id"    bigint NOT NULL,
 "quantity"       real NOT NULL DEFAULT 1,
 "recipent_id"    bigint NULL,
 "sender_id"      bigint NULL,
 CONSTRAINT "PK_Transaction_Instance" PRIMARY KEY ( "transaction_id", "instance_id" ),
 CONSTRAINT "FK_Instance" FOREIGN KEY ( "instance_id" ) REFERENCES "public"."Instance" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT "FK_Recipent" FOREIGN KEY ( "recipent_id" ) REFERENCES "public"."Character" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT "FK_Sender" FOREIGN KEY ( "sender_id" ) REFERENCES "public"."Character" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT "FK_Transaction" FOREIGN KEY ( "transaction_id" ) REFERENCES "public"."Transaction" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "FK_Instance" ON "public"."Transaction_Instances"
(
 "instance_id"
);

CREATE INDEX "FK_Recipent" ON "public"."Transaction_Instances"
(
 "recipent_id"
);

CREATE INDEX "FK_Sender" ON "public"."Transaction_Instances"
(
 "sender_id"
);

CREATE INDEX "FK_Transaction" ON "public"."Transaction_Instances"
(
 "transaction_id"
);

COMMENT ON TABLE "public"."Transaction_Instances" IS 'Transaction Instances';

COMMENT ON COLUMN "public"."Transaction_Instances"."transaction_id" IS 'ID of transaction';
COMMENT ON COLUMN "public"."Transaction_Instances"."instance_id" IS 'ID of an instance being transferred';
COMMENT ON COLUMN "public"."Transaction_Instances"."quantity" IS 'Amount being transferred';

COMMENT ON COLUMN "public"."Transaction_Instances"."sender_id" IS 'ID of sending Character';
COMMENT ON COLUMN "public"."Transaction_Instances"."recipent_id" IS 'ID of receiving Character';
